# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.105.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  private_lane :build_app do |options|
    match(
        type: "development",
        git_url: "https://github.com/ludoded/UnicornFastlaneCertificates"
    )
    
    increment_build_number
    
    gym( 
        workspace: "UnicornFastlane.xcworkspace",
        scheme: "UnicornFastlane", 
        use_legacy_build_api: true
    )
  end

  lane :beta do
    build_app
    
    # Ask the user of fastlane to enter a changelog
    changelog = prompt(text: "Enter the change log: ",
                       multi_line_end_keyword: "END")
    
    
    pilot(
      distribute_external: true,
      changelog: changelog,
      team_id: 550516
    )
    
    commit_version_bump(
      message: "Bump to version by fastlane",
      force: true
    )
    
    build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    add_git_tag(tag: "testflight-#{build_number}")
    
    push_to_git_remote
    
#    slack(
#      message: "Successfully deployed new App Update.",
#      payload: {
#        "Changes" => changelog
#      }
#    )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
